name: countries_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  ferry: ^0.8.0
  gql_http_link: ^0.3.2
  cupertino_icons: ^1.0.0
  ferry_flutter: ^0.3.0
  flutter: 
    sdk: flutter
  countries_client: 
    path: ../countries_client
dev_dependencies: 
  ferry_generator: ^0.3.0
  build_runner: ^1.10.2
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
